export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const USER_LOADED = "USER_LOADED"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const AUTH_ERROR = "AUTH_ERROR"
export const CLEAR_ERROR = "CLEAR_ERROR"

export const LOGOUT = "LOGOUT"



export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"

export const ADD_RESERVATION = "ADD_RESERVATION"
export const DELETE_RESERVATION = "DELETE_RESERVATION"
export const EDIT_RESERVATION = "EDIT_RESERVATION"